# Base image
FROM ubuntu:22.04

# Install required dependencies
RUN apt-get update -y && apt-get install -y \
    tzdata \
    software-properties-common \
    tar \
    curl \
 && rm -rf /var/lib/apt/lists/*

# Set timezone to UTC for global consistency
RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime && echo "UTC" > /etc/timezone

# Create a non-root user for running the app
RUN useradd -m -U -u 1001 fundtech
WORKDIR /home/fundtech/transaction-processor/

# Change ownership of working directory
RUN chown fundtech:fundtech /home/fundtech/transaction-processor/
USER fundtech

# Copy and extract the JDK
COPY --chown=fundtech:fundtech java/OpenJDK8U-jdk_x64_linux_hotspot_8u402b06.tar.gz .
RUN mkdir java && tar -C java -xzf OpenJDK8U-jdk_x64_linux_hotspot_8u402b06.tar.gz \
    && rm -f OpenJDK8U-jdk_x64_linux_hotspot_8u402b06.tar.gz

# Copy application-specific files
COPY --chown=fundtech:fundtech config/application.properties .
COPY --chown=fundtech:fundtech certs/rds-combined-ca-bundle.pem .
COPY --chown=fundtech:fundtech certs/cacerts .
COPY --chown=fundtech:fundtech target/transaction-processor-1.0.0.jar .

# Set environment profile (dev/stage/prod)
ARG PROFILE
ENV PROFILE=${PROFILE}

# Run the Java app
ENTRYPOINT ["./java/jdk8u402-b06/bin/java", "-Dspring.profiles.active=${PROFILE}", "-jar", "transaction-processor-1.0.0.jar"]
